import React from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";

//** Components */
import MainLayout from "@moduleComponents/MainLayout";

//** Styles */
import "./globals.css";

//** Meta data */
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

//** Global font */
const robotoFont = Roboto({
    weight: ["400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={robotoFont.className}>
            <body>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    );
}
